<?php
  include ("sys/header.php");
?>

<p><strong>I. &Aacute;ltal&aacute;nos felt&eacute;telek</strong><br />
			    1. A szerz&#337;d&#337; felek k&ouml;lcs&ouml;n&ouml;sen   k&ouml;telezetts&eacute;get v&aacute;llalnak a szerz&#337;d&eacute;sben foglaltak megtart&aacute;s&aacute;ra.<br />
			    2. A b&eacute;raut&oacute;   &aacute;tv&eacute;tel&eacute;t k&ouml;vet&#337;en minden reklam&aacute;ci&oacute;val k&ouml;teles a B&eacute;rl&#337; a B&eacute;rbead&oacute;hoz   fordulni.<br />
			    3. A jelen szerz&#337;d&eacute;st &eacute;rint&#337; b&aacute;rmely nyilatkozatot - a szerz&#337;d&eacute;sben   foglaltak kiv&eacute;tel&eacute;vel - kiz&aacute;r&oacute;lag &iacute;r&aacute;sban lehet &eacute;rv&eacute;nyesen megtenni. B&aacute;rmilyen   hamisadat szerz&#337;d&eacute;sbe foglal&aacute;sa, vagy a szerz&#337;d&eacute;s be nem tart&aacute;sa, a szerz&#337;d&eacute;s   azonnali hat&aacute;ly&uacute; felmond&aacute;s&aacute;t &eacute;s a v&eacute;tkes teljes k&aacute;rt&eacute;r&iacute;t&eacute;si felel&#337;ss&eacute;g&eacute;t vonja   maga ut&aacute;n.<br />
			    <strong>II. B&eacute;raut&oacute; haszn&aacute;lata</strong><br />
			    1. A b&eacute;raut&oacute; kiz&aacute;r&oacute;lag a   jogos&iacute;tv&aacute;nnyal rendelkez&#337; B&eacute;rl&#337; &aacute;ltal vezethet&#337;. A B&eacute;rl&#337;t felel&#337;ss&eacute;g terheli a   szerz&#337;d&eacute;st, a b&eacute;raut&oacute; &aacute;llag&aacute;t, jogi helyzet&eacute;t vagy egy&eacute;b k&ouml;r&uuml;lm&eacute;nyeit k&aacute;rosan   &eacute;rint&#337; k&ouml;vetkezm&eacute;nyek&eacute;rt, ezt eredm&eacute;nyez&#337; magatart&aacute;s&eacute;rt, cselekedet&eacute;rt.<br />
			    2.   B&eacute;rl&#337;nek tilos a b&eacute;raut&oacute;t alkoholos vagy k&aacute;b&iacute;t&oacute;szeres befoly&aacute;solts&aacute;g alatt   vezetnie. Tilos a b&eacute;raut&oacute;val b&uuml;ntetend&#337; cselekm&eacute;nyek elk&ouml;vet&eacute;se.<br />
			    3. A b&eacute;raut&oacute;   &aacute;rusz&aacute;ll&iacute;t&aacute;sra nem haszn&aacute;lhat&oacute;. B&eacute;rl&#337;nek tilos a b&eacute;raut&oacute;t sportrendezv&eacute;nyeken   neveznie &eacute;s/vagy tesztc&eacute;lokra haszn&aacute;lnia, valamint m&aacute;sik j&aacute;rm&#369;vet   vontatnia.<br />
			    <strong>III. B&eacute;rleti d&iacute;j, b&eacute;rleti id&#337; &eacute;s a b&eacute;raut&oacute;   visszaad&aacute;sa</strong><br />
			    1. A b&eacute;rleti d&iacute;j a B&eacute;rbead&oacute; mindenkor &eacute;rv&eacute;nyes &aacute;rlist&aacute;j&aacute;n   -melyet a www.localrent.hu port&aacute;lon tesz k&ouml;zz&eacute;-, vagy a B&eacute;rl&#337; &eacute;s a B&eacute;rbead&oacute;   k&ouml;z&ouml;tti meg&aacute;llapod&aacute;son alapul. A b&eacute;rleti d&iacute;j mag&aacute;ban foglalja a ken&#337;anyag, a   jav&iacute;t&aacute;s &eacute;s a k&ouml;telez&#337; felel&#337;ss&eacute;gbiztos&iacute;t&aacute;st. Az el&#337;rel&aacute;that&oacute; b&eacute;rleti d&iacute;j a   b&eacute;rlet kezdetekor fizetend&#337;.<br />
			    2. A b&eacute;raut&oacute;t, felszerel&eacute;seit, tartoz&eacute;kait &eacute;s a   j&aacute;rm&#369; okm&aacute;nyait a szerz&#337;d&eacute;sben meg&aacute;llap&iacute;tott b&eacute;rleti id&#337; lej&aacute;rta ut&aacute;n, az   &aacute;tad&aacute;skor megegyez&#337; &uuml;zemanyagszinttel (tele tank), k&iacute;v&uuml;l bel&uuml;l tiszt&aacute;n,   kifog&aacute;stalan &aacute;llapotban kell &aacute;tadni, a szerz&#337;d&eacute;sen szerepl&#337; id&#337;ben. A   meghat&aacute;rozott id&#337;n t&uacute;li visszav&eacute;tel eset&eacute;n (megkezdett &oacute;ra), extra napi   d&iacute;jszab&aacute;st sz&aacute;m&iacute;t fel, ami a napi b&eacute;rleti d&iacute;j. A b&eacute;raut&oacute; b&aacute;rmilyen tartoz&eacute;k&aacute;nak,   okm&aacute;ny&aacute;nak hi&aacute;nyz&aacute;sa eset&eacute;n (pl. forgalmi, rendsz&aacute;mt&aacute;bla, ind&iacute;t&oacute;kulcs, stb.)   p&oacute;td&iacute;jat sz&aacute;m&iacute;tunk fel. A p&oacute;td&iacute;jsz&aacute;m&iacute;t&aacute;s alapja a keletkezett k&ouml;lts&eacute;gek, plusz   az &uuml;gyint&eacute;z&eacute;si d&iacute;j. A visszaad&aacute;s t&eacute;ny&eacute;t, kilom&eacute;ter&oacute;ra &aacute;ll&aacute;s&aacute;t &eacute;s az esetleges &uacute;j   s&eacute;r&uuml;l&eacute;seket a b&eacute;raut&oacute;n, a szerz&#337;d&eacute;s megszeg&eacute;s&eacute;t, a felek a b&eacute;rleti szerz&#337;d&eacute;sen,   a visszav&eacute;telkor al&aacute;&iacute;r&aacute;sukkal hiteles&iacute;tik.<br />
			    3. A B&eacute;rl&#337; viseli a b&eacute;rlet   id&#337;tartama alatt a b&eacute;raut&oacute; rendeltet&eacute;sszer&#369; haszn&aacute;lat&aacute;val kapcsolatos valamennyi   k&ouml;lts&eacute;get (pl.: &uuml;zemanyagk&ouml;lts&eacute;g, aut&oacute;p&aacute;lyad&iacute;j, parkol&aacute;si d&iacute;j, gar&aacute;zs d&iacute;j,   b&iacute;rs&aacute;gok stb.).<br />
			    4. A B&eacute;rbead&oacute; jogosult a szerz&#337;d&eacute;s azonnali felmond&aacute;s&aacute;ra, ha   a B&eacute;rl&#337; a szerz&#337;d&eacute;st megszegi. Ebben az esetben a B&eacute;rbead&oacute;nak joga van a   b&eacute;raut&oacute;t &ouml;nhatalm&uacute;lag visszavennie a B&eacute;rl&#337;t&#337;l.<br />
			    5. A B&eacute;rl&#337; felt&eacute;tlen&uuml;l &eacute;s   visszavonhatatlanul hozz&aacute;j&aacute;rul ahhoz, hogy amennyiben b&aacute;rmilyen m&oacute;don   ellen&aacute;ll&aacute;st tan&uacute;s&iacute;tana b&eacute;raut&oacute; a B&eacute;rbe ad&oacute;, vagy ennek igazolt meghatalmazottja   &aacute;ltal t&ouml;rt&eacute;n&#337; elsz&aacute;ll&iacute;t&aacute;s&aacute;val szemben, a B&eacute;rbead&oacute; vagy az igazolt   meghatalmazottja jogosult a B&eacute;rl&#337; ellen&aacute;ll&aacute;s&aacute;t megt&ouml;rni &eacute;s a b&eacute;raut&oacute;t saj&aacute;t   birtok&aacute;ba vonni. A B&eacute;rl&#337; kifejezetten meger&#337;s&iacute;ti, hogy az ellen&aacute;ll&aacute;s el&#337;z&#337;ek   szerinti megt&ouml;r&eacute;se nem min&#337;s&uuml;l tilos &ouml;nhatalomnak illetve   &ouml;nb&iacute;r&aacute;skod&aacute;snak.<br />
			    <strong>IV. Biztos&iacute;t&aacute;s</strong><br />
			    1. A B&eacute;rl&#337; &aacute;ltal fizetend&#337; d&iacute;j   mag&aacute;ban foglalja a Magyarorsz&aacute;gon t&ouml;rv&eacute;ny szerint el&#337;&iacute;rt k&ouml;telez&#337;   felel&#337;ss&eacute;gbiztos&iacute;t&aacute;st.<br />
			    2. A b&eacute;raut&oacute;val t&ouml;rt&eacute;nt v&eacute;tlen baleset eset&eacute;n minden   esetben sz&uuml;ks&eacute;g van rend&#337;ri int&eacute;zked&eacute;sre, rend&#337;ri igazol&aacute;sra a balesetr&#337;l, egy   szab&aacute;lyosan kit&ouml;lt&ouml;tt, minden balesetben r&eacute;sztvev&#337; f&eacute;l &aacute;ltal al&aacute;&iacute;rt, eur&oacute;pai   form&aacute;tum&uacute; baleseti bejelent&#337;re. Ennek hi&aacute;ny&aacute;ban a teljes k&aacute;rt a B&eacute;rl&#337;nek kell   megt&eacute;r&iacute;tenie.<br />
			    3. A b&eacute;rleti d&iacute;j tartalmazza a bizonyos b&eacute;raut&oacute;kra CASCO biztos&iacute;t&aacute;s&aacute;t   t&ouml;r&eacute;sk&aacute;r eset&eacute;re, a B&eacute;rl&#337; felel&#337;ss&eacute;ge t&ouml;r&eacute;sk&aacute;r eset&eacute;n, amennyiben a szerz&#337;d&eacute;sben   foglaltakat betartotta, csak a casco &ouml;nr&eacute;szre terjed ki.<br />
			    4. A b&eacute;rleti d&iacute;j   tartalmazza bizonyos b&eacute;raut&oacute;kra vonatkoz&oacute; CASCO biztos&iacute;t&aacute;st lop&aacute;sk&aacute;r eset&eacute;re, a B&eacute;rl&#337;   felel&#337;ss&eacute;ge lop&aacute;sk&aacute;r eset&eacute;n, amennyiben a szerz&#337;d&eacute;st betartotta a b&eacute;rl&#337;, csak a   casco &ouml;nr&eacute;szre terjed ki.<br />
			    5. A CASCO biztos&iacute;t&aacute;s t&ouml;r&eacute;sk&aacute;r &eacute;s lop&aacute;sk&aacute;r eset&eacute;re   b&aacute;rmilyen szerz&#337;d&eacute;sszeg&eacute;s, vagy hamis, val&oacute;tlan vagy megt&eacute;veszt&#337; adat k&ouml;zl&eacute;se   eset&eacute;n, teljes k&aacute;rt&eacute;r&iacute;t&eacute;si felel&#337;ss&eacute;ggel tartozik a B&eacute;rl&#337;. A CASCO biztos&iacute;t&aacute;s   t&ouml;r&eacute;sk&aacute;r &eacute;s lop&aacute;sk&aacute;r eset&eacute;re hat&aacute;lytalan &eacute;s teljes k&aacute;rt&eacute;r&iacute;t&eacute;si felel&#337;ss&eacute;ggel   tartozik a B&eacute;rl&#337;, ha a b&eacute;raut&oacute; forgalmi enged&eacute;ly&eacute;t &eacute;s eredeti kulcs&aacute;t nem adta   vissza a B&eacute;rbead&oacute;nak, vagy a b&eacute;raut&oacute; kulcs&aacute;t lem&aacute;soltatta. A B&eacute;rbead&oacute; lop&aacute;sk&aacute;r   eset&eacute;n a kulcsot szak&eacute;rt&#337;vel megvizsg&aacute;ltatja.<br />
			    6. A b&eacute;raut&oacute;n bek&ouml;vetkez&#337;   ker&eacute;kk&aacute;rokra (felni s&eacute;r&uuml;l&eacute;se, ellop&aacute;sa), a gumiabroncs s&eacute;r&uuml;l&eacute;s&eacute;re, a g&eacute;pj&aacute;rm&#369;   bels&#337; ter&eacute;nek &eacute;s csomagter&eacute;nek, nem v&eacute;tlen balesetb&#337;l ered&#337; k&aacute;rosod&aacute;s&aacute;ra a CASCO   biztos&iacute;t&aacute;s nem vonatkozik, ezek&eacute;rt a B&eacute;rl&#337; teljes anyagi felel&#337;ss&eacute;ggel   tartozik.<br />
			    7. A b&eacute;raut&oacute; b&aacute;rmilyen r&ouml;vid id&#337;re &#337;rizetlen&uuml;l hagy&aacute;sa eset&eacute;n a   B&eacute;rl&#337; k&ouml;teles a leszedhet&#337; el&#337;lap&uacute; aut&oacute;r&aacute;di&oacute; el&#337;lapj&aacute;t mag&aacute;val vinni, valamint   gondoskodni arr&oacute;l, hogy &eacute;rt&eacute;kt&aacute;rgy ne maradjon a b&eacute;raut&oacute;ban. Ellenkez&#337; esetben a   B&eacute;rl&#337;t teljes k&aacute;rt&eacute;r&iacute;t&eacute;si felel&#337;ss&eacute;g terheli, &eacute;s a CASCO szerz&#337;d&eacute;s hat&aacute;ly&aacute;t   veszti.<br />
			    8. A b&eacute;raut&oacute; ind&iacute;t&oacute;kulcs&aacute;nak elveszt&eacute;se eset&eacute;n azonnal &eacute;rtes&iacute;teni   kell a B&eacute;rbead&oacute;t. Az ezzel kapcsolatos &ouml;sszes k&ouml;lts&eacute;get a B&eacute;rl&#337; fizeti.<br />
			    <strong>V.   B&eacute;rl&#337; magatart&aacute;sa baleset ill. k&aacute;resem&eacute;ny eset&eacute;n</strong><br />
			    1. A B&eacute;rl&#337; (jogosult   vezet&#337;) balesetekn&eacute;l/egy&eacute;b k&aacute;rokn&aacute;l k&ouml;teles k&ouml;zvetlen&uuml;l &eacute;s halad&eacute;ktalanul, de   legk&eacute;s&#337;bb 24 &oacute;r&aacute;n bel&uuml;l a B&eacute;rbead&oacute;t &eacute;s a rend&#337;rs&eacute;get &eacute;rtes&iacute;teni, a   k&aacute;rn&aacute;l/balesetn&eacute;l r&eacute;sztvev&#337;ket &eacute;s az esetleges tan&uacute;kat n&eacute;v &eacute;s c&iacute;m szerint   jegyz&#337;k&ouml;nyveztetni.<br />
			    2. K&aacute;rnyilatkozatot &aacute;tadni csak a B&eacute;rbead&oacute;   beleegyez&eacute;s&eacute;vel megengedett. A sz&uuml;ks&eacute;ges ment&eacute;si &eacute;s jav&iacute;t&aacute;si int&eacute;zked&eacute;sek minden   esetben a B&eacute;rbead&oacute; feladatai, azokat &#336; kezdem&eacute;nyezi.<br />
			    3. A B&eacute;rl&#337; k&ouml;telezi   mag&aacute;t, hogy k&eacute;sedelem n&eacute;lk&uuml;l r&eacute;szletes baleseti jelent&eacute;st k&eacute;sz&iacute;t a B&eacute;rbead&oacute;nak.   A B&eacute;rl&#337; teljes m&eacute;rt&eacute;kben felel&#337;ss&eacute;gre vonhat&oacute;, ha a B&eacute;rbead&oacute;t nem &eacute;rtes&iacute;ti   k&eacute;sedelem n&eacute;lk&uuml;l, legk&eacute;s&#337;bb 24 &oacute;r&aacute;val a baleset, lop&aacute;s vagy a b&eacute;raut&oacute; felt&ouml;r&eacute;se   eset&eacute;n.<br />
			    4. Amennyiben a B&eacute;rl&#337; a k&aacute;r&uuml;gyint&eacute;z&eacute;shez sz&uuml;ks&eacute;ges okm&aacute;nyokat nem   adja le a k&aacute;resem&eacute;nyt k&ouml;vet&#337; 24 &oacute;r&aacute;n bel&uuml;l, a k&eacute;sedelmes jav&iacute;t&aacute;si &eacute;s &uuml;gyint&eacute;z&eacute;si   id&#337;b&#337;l ered&#337; k&aacute;rokat k&ouml;teles a B&eacute;rbead&oacute;nak megt&eacute;r&iacute;teni.<br />
			    5. Lop&aacute;sk&aacute;r eset&eacute;n a   B&eacute;rl&#337; k&ouml;teles halad&eacute;ktalanul feljelent&eacute;st tenni a rend&#337;rs&eacute;gen is, az err&#337;l   k&eacute;sz&uuml;lt jegyz&#337;k&ouml;nyvet a B&eacute;rbead&oacute; rendelkez&eacute;s&eacute;re bocs&aacute;tania.<br />
			    <strong>VI. A b&eacute;raut&oacute;   meghib&aacute;sod&aacute;sa</strong><br />
			    1. A B&eacute;rbead&oacute; v&aacute;llalja a b&eacute;raut&oacute;n el&#337;fordul&oacute; jav&iacute;t&aacute;si   k&ouml;lts&eacute;geket, amennyiben azok a rendeltet&eacute;sszer&#369; (az &uuml;zemeltet&eacute;s &eacute;s/vagy a   k&ouml;zleked&eacute;s biztons&aacute;g&aacute;nak megfelel&#337;) haszn&aacute;lat sor&aacute;n keletkeznek. A B&eacute;rl&#337;,   amennyiben meghib&aacute;sod&aacute;st &eacute;szlelt, k&ouml;teless&eacute;ge azt telefonon a B&eacute;rbead&oacute;nak   bejelentenie.<br />
			    2. A kilom&eacute;ter-sz&aacute;ml&aacute;l&oacute; meghib&aacute;sod&aacute;s&aacute;n&aacute;l a B&eacute;rbead&oacute;t   halad&eacute;ktalanul &eacute;rtes&iacute;teni kell.<br />
			    3. A B&eacute;rl&#337; a b&eacute;raut&oacute; &uuml;zembiztons&aacute;ga &eacute;rdek&eacute;ben   k&ouml;teles ellen&#337;rizni a j&aacute;rm&#369; h&#369;t&#337;v&iacute;z folyad&eacute;kszintj&eacute;t, motorolajat, &eacute;s k&ouml;teles   jelezni a h&#369;t&#337;v&iacute;z folyad&eacute;kszintj&eacute;vel, a motor- &eacute;s a sebess&eacute;gv&aacute;lt&oacute;-olajjal   kapcsolatos probl&eacute;m&aacute;kat. A h&#369;t&#337; vagy ken&#337;folyad&eacute;k elfoly&aacute;sa miatti k&aacute;r eset&eacute;n a   keletkezett k&aacute;r&eacute;rt a B&eacute;rl&#337; felel.<br />
			    4. A B&eacute;rl&#337; teljes &eacute;s felt&eacute;tlen k&aacute;rt&eacute;r&iacute;t&eacute;si   k&ouml;telezetts&eacute;ggel tartozik, az el&#337;z&#337; (VI/1, VI/2, VI/3,) pontokban foglaltak   elmulaszt&aacute;sa, valamint gondatlan, nem rendeltet&eacute;sszer&#369; haszn&aacute;latb&oacute;l ered&#337;, a   b&eacute;raut&oacute;n keletkezett karossz&eacute;ria, alv&aacute;z, fut&oacute;m&#369;, f&eacute;krendszer &eacute;s minden egy&eacute;b   r&eacute;sz k&aacute;rosod&aacute;sa eset&eacute;n.<br />
			    <strong>VII. B&eacute;rl&#337; felel&#337;ss&eacute;ge</strong><br />
			    1. A B&eacute;rl&#337; felel&#337;s   minden, a b&eacute;rleti id&#337; alatt a b&eacute;raut&oacute;n el&#337;&aacute;llt jogi, p&eacute;nz&uuml;gyi &eacute;s egy&eacute;b   h&aacute;tr&aacute;nyok&eacute;rt &eacute;s k&aacute;rok&eacute;rt, bele&eacute;rtve a b&eacute;raut&oacute;nak a biztons&aacute;gos k&ouml;zleked&eacute;sre   vonatkoz&oacute; hi&aacute;nyoss&aacute;gait is.<br />
			    2. B&eacute;rbead&oacute; a B&eacute;rl&#337;re terheli a B&eacute;rl&#337; &aacute;ltal   okozott &ouml;sszes k&aacute;rt &eacute;s j&aacute;rul&eacute;kos k&ouml;lts&eacute;geket (pl.: szakv&eacute;lem&eacute;ny, vontat&aacute;si   k&ouml;lts&eacute;gek, napid&iacute;jak). A B&eacute;rbead&oacute; ragaszkodik k&aacute;rt&eacute;r&iacute;t&eacute;si   ig&eacute;ny&eacute;hez/ig&eacute;nyeihez.<br />
			    3. A B&eacute;rl&#337; k&ouml;teles a b&eacute;rl&eacute;s ideje alatt a b&eacute;raut&oacute;ra   kiszabott b&iacute;rs&aacute;gok &eacute;s egy&eacute;b t&eacute;r&iacute;t&eacute;si d&iacute;jak (parkol&oacute;jegy, gyorshajt&aacute;s, stb.)   megfizet&eacute;s&eacute;re. Amennyiben valamely b&iacute;rs&aacute;got a b&eacute;rl&eacute;s ut&aacute;n ut&oacute;lag, a B&eacute;rbead&oacute;   k&ouml;zbenj&aacute;r&aacute;s&aacute;val fizeti meg a b&eacute;rl&#337;, a b&iacute;rs&aacute;gon fel&uuml;l az &uuml;gyint&eacute;z&eacute;si d&iacute;jat is meg   kell fizetnie a B&eacute;rl&#337;nek.<br />
			    4. A B&eacute;rl&#337; a b&eacute;raut&oacute;t, annak tartoz&eacute;kait j&oacute; gazda   m&oacute;dj&aacute;ra k&ouml;teles haszn&aacute;lni &eacute;s a b&eacute;raut&oacute;, valamint okm&aacute;nyainak &#337;rz&eacute;s&eacute;r&#337;l   gondoskodni.<br />
			    5. A B&eacute;rl&#337; teljes k&aacute;rt&eacute;r&iacute;t&eacute;si felel&#337;ss&eacute;ggel tartozik, ha a   b&eacute;raut&oacute;t alkoholos, vagy k&aacute;b&iacute;t&oacute;szeres &eacute;s/vagy egy&eacute;b b&oacute;dulatkelt&eacute;sre alkalmas   szer befoly&aacute;solts&aacute;g alatt vezette, a g&eacute;pkocsit nem a szerz&#337;d&eacute;sben megjel&ouml;lt   szem&eacute;ly vezette, tov&aacute;bb&aacute;, ha a k&aacute;r m&aacute;s j&aacute;rm&#369; vontat&aacute;sa k&ouml;zben   keletkezett.<br />
			    <strong>VIII. Fizet&eacute;si &eacute;s p&eacute;nz&uuml;gyi felt&eacute;telek</strong><br />
			    1. A B&eacute;rl&#337; a   b&eacute;rleti d&iacute;jat, az el&#337;re l&aacute;that&oacute; k&ouml;lts&eacute;geket el&#337;re k&ouml;teles kifizetni!<br />
			    2.   Fizet&eacute;si k&eacute;sedelem eset&eacute;n a k&eacute;sedelmi kamat m&eacute;rt&eacute;ke az aktu&aacute;lis jegybanki   alapkamat k&eacute;tszeres&eacute;vel egyenl&#337;, a B&eacute;rbead&oacute; kamatos kamatot sz&aacute;m&iacute;t fel.<br />
			    3. A   B&eacute;rl&#337; a szerz&#337;d&eacute;s al&aacute;&iacute;r&aacute;s&aacute;val egyoldal&uacute; k&ouml;telezetts&eacute;get v&aacute;llal arra, hogy   rendeltet&eacute;s ellenes haszn&aacute;latb&oacute;l, jelen szerz&#337;d&eacute;s vagy a b&eacute;rleti szerz&#337;d&eacute;s &eacute;s a   b&eacute;rleti felt&eacute;telek megszeg&eacute;s&eacute;b&#337;l, vagy egy&eacute;b k&aacute;rokoz&aacute;sb&oacute;l ered&#337;en a b&eacute;raut&oacute;ban,   vagy annak tartoz&eacute;kaiban k&aacute;r keletkezik, a k&aacute;r &ouml;sszeg&eacute;t k&eacute;szp&eacute;nzben, a k&aacute;r   meg&aacute;llap&iacute;t&aacute;s&aacute;t&oacute;l sz&aacute;m&iacute;tott 8 napon bel&uuml;l megt&eacute;r&iacute;ti. A B&eacute;rl&#337; jogosult a k&aacute;r   meg&aacute;llap&iacute;t&aacute;s&aacute;hoz f&uuml;ggetlen igazs&aacute;g&uuml;gyi szak&eacute;rt&#337;, vagy hivatalos m&aacute;rkaszerviz   szakv&eacute;lem&eacute;ny&eacute;t k&eacute;rni.<br />
			    4. A B&eacute;rl&#337; a szerz&#337;d&eacute;s al&aacute;&iacute;r&aacute;s&aacute;val egyoldal&uacute; &eacute;s   visszavonhatatlan k&ouml;telezetts&eacute;get v&aacute;llal arra, hogy amennyiben a b&eacute;rleti   felt&eacute;teleket megszegi, az ebb&#337;l ered&#337; fizetend&#337; p&oacute;td&iacute;jakat halad&eacute;ktalanul (a   b&eacute;raut&oacute; visszaad&aacute;sakor) k&eacute;szp&eacute;nzben megfizeti.<br />
			    5. A B&eacute;rleti felt&eacute;telek   megszeg&eacute;sekor fizetend&#337; p&oacute;td&iacute;j fizet&eacute;si k&ouml;telezetts&eacute;g meg&aacute;llap&iacute;t&aacute;s&aacute;val   kapcsolatban, a szerz&#337;d&#337; felek k&ouml;z&ouml;tt esetleg felmer&uuml;l&#337; (jog)vita eset&eacute;n, mindig   a B&eacute;rbead&oacute; &aacute;ll&aacute;spontja az ir&aacute;nyad&oacute;, ennek ellenkez&#337;j&eacute;t a B&eacute;rl&#337;nek kell hitelt   &eacute;rdeml&#337;en bizony&iacute;tania.<br />
			    <strong>IX. Adatv&eacute;delem</strong><br />
			    1. A B&eacute;rbead&oacute; k&ouml;telezi   mag&aacute;t, hogy a B&eacute;rl&#337;r&#337;l tudom&aacute;s&aacute;ra jutott t&aacute;rolt adatokat kiz&aacute;r&oacute;lag a b&eacute;rbead&aacute;si   egy&uuml;ttm&#369;k&ouml;d&eacute;s &eacute;rdek&eacute;ben, vagy saj&aacute;t &eacute;rt&eacute;kes&iacute;t&eacute;si &eacute;s marketing c&eacute;lokra haszn&aacute;lja,   azokat harmadik f&eacute;lnek ki nem adja.<br />
			    2. Abban az esetben, ha a B&eacute;rl&#337; a   j&aacute;rm&#369;vet a szerz&#337;d&eacute;s lej&aacute;rta ut&aacute;n 24 &oacute;r&aacute;n bel&uuml;l nem szolg&aacute;ltatja vissza, illetve   az esed&eacute;kes b&eacute;rleti d&iacute;jakat, p&oacute;td&iacute;jakat, vagy k&ouml;lts&eacute;gt&eacute;r&iacute;t&eacute;st nem fizeti   pontosan, vagy a B&eacute;rl&#337; b&eacute;rleti szerz&#337;d&eacute;sben szerepl&#337; adatai nem val&oacute;diak, vagy   b&aacute;rmely egy&eacute;b jogvita eset&eacute;n, a B&eacute;rbead&oacute; jogosult a szem&eacute;lyi adatokat harmadik   szem&eacute;lynek &aacute;tadni.<br />
			    <strong>X. Egy&eacute;b rendelkez&eacute;sek</strong><br />
			    1. A jelen szerz&#337;d&eacute;sb&#337;l   ered&#337; jogvita eset&eacute;re, a Budapesti III. ker&uuml;leti B&iacute;r&oacute;s&aacute;g a kiz&aacute;r&oacute;lagos illet&eacute;kes.<br />
			    2. A   szerz&#337;d&#337; felek kijelentik, hogy ha a szerz&#337;d&eacute;si rendelkez&eacute;sekb&#337;l b&aacute;rmely   felt&eacute;tel semmis lenne, a szerz&#337;d&eacute;st a szerz&#337;d&#337; felek e felt&eacute;tel n&eacute;lk&uuml;l is   megk&ouml;tn&eacute;k.<br />
			    3. A szerz&#337;d&eacute;sben nem szab&aacute;lyozott k&eacute;rd&eacute;sekre a Polg&aacute;ri   T&ouml;rv&eacute;nyk&ouml;nyv (1959. &eacute;vi IV. t&ouml;rv&eacute;ny) hat&aacute;lyos rendelkez&eacute;seit kell   alkalmazni<br />
			    <strong>XI. Z&aacute;r&oacute; megjegyz&eacute;sek</strong><br />
		      1. A B&eacute;rl&#337;, a b&eacute;rleti szerz&#337;d&eacute;s   al&aacute;&iacute;r&aacute;s&aacute;val elfogadja az azon szerepl&#337; b&eacute;rleti &aacute;rakat &eacute;s egy&eacute;b (p&oacute;t) d&iacute;jakat,   tov&aacute;bb&aacute; kijelenti, hogy a b&eacute;rleti szerz&#337;d&eacute;st &eacute;s az &aacute;ltal&aacute;nos szerz&#337;d&eacute;si   felt&eacute;teleket elolvasta, az abban foglaltakat tudom&aacute;sul vette, &eacute;s azok be nem   tart&aacute;s&aacute;b&oacute;l ered&#337; k&ouml;vetkezm&eacute;nyeket viseli.</p>
<?php
  include ("sys/footer.php");
?>